org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.42
forge_version_range=[36.2.42,37)
loader_version_range=[36,37)
mapping_channel=official
mapping_version=1.16.5

mod_id=castlewars
mod_name=Castle Wars
mod_license=All Rights Reserved
mod_version=0.2.0
mod_group_id=com.aleksandreev.castlewars
mod_authors=aleksandreev2
mod_description=Two-castle siege PvP. Breach gates or flank routes, contest the War Camp, destroy the enemy Castle Core, then defeat the defender to score. First to 10 wins.
